### ISSUE TITLE
Add XLAM -> vbaProject.bin Functionality

### ISSUE THREAD

**Issue by jimbrig** [Beakerboy/Excel-Addin-Generator#3]
Just wondering if you still plan to incorporate this feature. The code is currently commented on in `main.py`

**Comment by Beakerboy** [comment]
I have not worked on this in quite some time. Last I remember it only kind of worked. I need to figure out how to test that the result file works and place that code in a testing environment. I think python has libraries to interact with xls files.

**Comment by jimbrig** [comment]
@Beakerboy thanks for the response. I understand that. I was able to create some simple powershell scripts to do this for me but came across your code while doing some investigation for a project that attempts to extract/compile/import and export all the various components of an excel workbook to aid devs and had not seen much dealing with the vbaProject.bin extraction itself (which in turn needs to be uncompressed again to get to the XML'ish vbaProject metadata and code mappings, etc.).

**Comment by jimbrig** [comment]
Will go ahead and close this out.

**Comment by Beakerboy** [comment]
I'm more than happy to accept code that adds functionality. My overall idea is to be able to store VBA code on github, and have scripts that can package it all up into an xla file to create automated releases on github. The hardest step is "compiling" the vba into the  vbaProject.bin file. [VBAPackager](https://github.com/sancarn/VBAPackager) aims to accomplish this part. My project aims to accomplish the final step, of inserting a working vbaProject.bin into a blank shell for distribution.

**Comment by Beakerboy** [comment]
I added some untested code that might work for you. Try it out and let me know.

**Comment by Beakerboy** [comment]
I added some tests, so at least in theory, it should work.
